### ISSUE TITLE
Bug:{product-long} is not  working on local  

### ISSUE THREAD

**Issue by ajaypratap003** [redhat-developer/app-services-guides#97] opened 2021-04-16 09:48 UTC
Bug:{product-long} is not  working on local  

![image](https://user-images.githubusercontent.com/11775081/115006504-97a7c580-9ec6-11eb-8eb0-8b22d4e1b817.png)

**Comment by wtrocki** [comment] 2021-04-16 10:35
Duplicate of https://github.com/redhat-developer/app-services-guides/issues/94

**Closed by wtrocki** 2021-04-16 10:35 UTC
Labels: bug
